# some more ls aliases
alias cl='clang++ -std=c++11'
alias clip='xsel -b -i'
alias dir='dir --color=auto'
alias done='sudo shutdown now'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias kshutdown='qdbus org.kde.ksmserver /KSMServer logout 0 2 2' #kde shutdown
alias l.='ls -d .* --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ld='ls -d */'
alias lg='ls --group-directories-first --color=auto'
alias ll='ls -alF'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias lt='ls --group-directories-first --color=auto --sort=time'
alias lx='ls -x'
alias md='mkdir'
alias run='./a.out'
alias upable='sudo apt list --upgradable'
alias update='sudo apt update'
alias upgradabale='sudo apt list --upgradable'
alias upgrade='sudo apt upgrade'
alias vdir='vdir --color=auto'
alias vi='vim'
alias vim='vim.gtk3'
alias vless='/usr/share/vim/vim74/macros/less.sh'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias x='xdg-open'
alias xclip='xclip --selection c'
# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
alias nm='neomutt'
alias gmail='neomutt'
