"Grab the global vimrc"
source $VIM\_vimrc
colorscheme= gruvbox
"----- GUI settings -----"
set guifont=hack\ 14
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar

